### ISSUE TITLE
clean-css 的版本太老

### ISSUE THREAD

**Issue by jiangyuan** [fex-team/fis-optimizer-clean-css#1]
如题， clean-css 的版本太老，是时候更新下了。

**Comment by oxUnd** [comment]
先用这个 fis-optimizer-clean-css-2x@0.2.0

配置方法

``` javascript
fis.config.set('modules.optimizer.css', 'clean-css-2x');
```

**Comment by jiangyuan** [comment]
所有插件都在 global ，在版本管理上确实有点蛋疼。

**Comment by fouber** [comment]
@jiangyuan 

是为了构建环境的一致性和唯一性，团队使用的时候通常会共享一个构建环境，这样才能确保每次构建的安全，所以插件设计是全局安装的

**Comment by jincdream** [comment]
``` sass
$a : #fcc;
div{
  background: $a;
}
div{
  background: #000123;
}
```

目前我手动更新 clean css 到3.0+ 这个div终于被压缩了，在目前1.0+ 是没有被压缩的。~2.0+没测试过了。

**Comment by oxUnd** [comment]
@jincdream 好的，我们搞一个 3.0 版本的插件，或者你自己来一个也行。因为升级压缩器需要大量的测试，我们就是由于某个时刻没有测试压缩器导致上线挂掉过。

**Comment by jincdream** [comment]
恩，我开个分支先吧。
